# .pre-commit-config.yaml
# ========================
#
# pre-commit clean
# pre-commit install
# pre-commit install-hooks
#
# precommit hooks installation
#
# - pre-commit autoupdate
#
# - pre-commit run black
#
# continuous integration
# ======================
#
# - pre-commit run --all-files
#

default_stages:
  - pre-commit

default_install_hook_types:
  - pre-commit
  - commit-msg
  - pre-push

exclude: pypoetry

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
        exclude: poetry.lock
      - id: debug-statements
      - id: check-merge-conflict
      - id: sort-simple-yaml
      - id: fix-encoding-pragma
        args: ["--remove"]
      - id: forbid-new-submodules
      - id: mixed-line-ending
        args: ["--fix=lf"]
        description: Forces to replace line ending by the UNIX "lf" character.
      - id: check-added-large-files
        args: ["--maxkb=500"]
      - id: no-commit-to-branch
        args: [--branch, main]
      - id: check-yaml
        args: [--allow-multiple-documents]
      - id: check-toml
      - id: check-json
        files: ^tests/app/
      - id: pretty-format-json
        args: ["--no-sort-keys", "--autofix"]
        files: ^tests/app/

  - repo: https://github.com/ambv/black
    rev: 24.4.2
    hooks:
      - id: black

  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.8
    hooks:
      - id: bandit
        description: Security oriented static analyser for python code
        exclude: tests/|scripts/|lib/helpers
        args:
          - -s
          - B101,B311,B105

  - repo: https://github.com/jendrikseipp/vulture
    rev: v2.11
    hooks:
      - id: vulture
        description: Find dead Python code
        args:
          [
            "--min-confidence",
            "90",
            "--exclude",
            "tests,env,lib/schemas/fields.py,.tox",
            "--ignore-names",
            "einfo,task_id,retval,logger,log_method,exc,args",
            ".",
          ]

  - repo: https://github.com/codespell-project/codespell
    rev: v2.3.0
    hooks:
      - id: codespell
        name: codespell
        description: Checks for common misspellings in text files.
        language: python
        types: [text]
        additional_dependencies:
          - tomli

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.4.6
    hooks:
      - id: ruff

  - repo: https://github.com/dosisod/refurb
    rev: v2.0.0
    hooks:
      - id: refurb

  - repo: https://github.com/commitizen-tools/commitizen
    rev: v3.27.0
    hooks:
      - id: commitizen
        stages:
          - commit-msg
      - id: commitizen-branch
        stages:
          - pre-push
        args:
          - --rev-range
          - HEAD^!
        always_run: true
        pass_filenames: false
